### ISSUE TITLE
Dashboard gets wrong ExeExitCode

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#100]
When executing `cmsRun` fails (in this case due to the cache still being populated), the dashboard gets an execution exit code of 0, where it should get 126.

```
--- Running cmsRun
cmsRun -j report.xml "makeBEAN_cfg_mod.py"  > cmssw.log 2>&1
---
Traceback (most recent call last):
  File "job.py", line 63, in check_execution
    yield
  File "job.py", line 457, in <module>
    cputime = extract_info(config, data, 'report.xml')
  File "job.py", line 291, in extract_info
    with open(report_filename) as f:
IOError: [Errno 2] No such file or directory: 'report.xml'

Traceback (most recent call last):
  File "job.py", line 63, in check_execution
    yield
  File "job.py", line 484, in <module>
    copy_outputs(data, config, env)
  File "job.py", line 205, in copy_outputs
    outsize += os.path.getsize(localname)
  File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw-patch/CMSSW_5_3_15_patch1/external/slc5_amd64_gcc462/bin/../../../../../../external/python/2.6.4/lib/python2.6/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'merged_bean.root'

Execution time 151
Exiting with code 126
Reporting ExeExitCode 0
Reporting StageOutExitCode 0
```

**Comment by matz-e** [comment]
Marking this as fixed for now with the latest changes in master — I see error codes such as `-11` in the logs at the dashboard update stage.
