### ISSUE TITLE
Transient TestChirpPermissions failure

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#237]
`test_se.TestChirpPermissions` fails transiently with this error:

```
======================================================================
ERROR: runTest (test_se.TestChirpPermissions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/test/test_se.py", line 103, in runTest
    self.permissions('chirp://localhost:' + self.port)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/test/test_se.py", line 49, in permissions
    fs.makedirs('ham/eggs')
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/se.py", line 110, in makedirs
    self.makedirs(parent)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/se.py", line 114, in makedirs
    self.mkdir(path, mode=mode)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/se.py", line 68, in switch
    return imp.fixresult(getattr(imp, attr)(*map(imp.lfn2pfn, args), **kwargs))
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/se.py", line 252, in mkdir
    self.__c.chmod(path, mode)
  File "/afs/crc.nd.edu/group/ccl/software/cctools-042-033bd0d4-cvmfs-40cf5bba/x86_64/redhat6/lib/python2.6/site-packages/Chirp.py", line 1090, in chmod
    raise GeneralFailure('chmod', result)
TypeError: __init__() takes exactly 4 arguments (3 given)
```

I haven't dug around yet, it is not obvious why the error isn't deterministic...

**Comment by matz-e** [comment]
Is this still an issue? IIRC, this was more a failure of the cctools than an issue with our code…

**Comment by matz-e** [comment]
This hasn't shown up in CI for a while, so I'm closing the issue. Feel free to reopen, if it pops up again.
