### ISSUE TITLE
Plotting Ties Up DB in Long Runs?

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#265]
This is hypothetical, but I think that perhaps, as a run gets long, the DB access for plotting grows so long that it can cause issues.  Here are the factors that lead me to this hypothesis:

1.  I had a master crash after running smoothly for a week due to what looks like a DB error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/commands/process.py", line 299, in sprint
    task_src.release(tasks)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/source.py", line 427, in release
    self.__store.register_files(infos, label)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/unit.py", line 252, in register_files
    self.update_workflow_stats(label, total=True)
OperationalError: database is locked
```
Note: the master died around 6am today and from the log it looks like it was trying to plot:
```
2016-01-06 05:40:56 [DEBUG] lobster.plotting: reading database
2016-01-06 05:41:16 [DEBUG] lobster.plotting: finished reading database
```

2.  The time to access the DB for plotting gets fairly long as the run progresses.  Compare some log-file excerpts from the start of the run and now (nearing the end):
Start:
```
2015-12-27 15:25:57 [DEBUG] lobster.plotting: reading database
2015-12-27 15:25:57 [DEBUG] lobster.plotting: finished reading database
2015-12-27 15:41:02 [DEBUG] lobster.plotting: reading database
2015-12-27 15:41:02 [DEBUG] lobster.plotting: finished reading database
2015-12-27 15:56:05 [DEBUG] lobster.plotting: reading database
2015-12-27 15:56:05 [DEBUG] lobster.plotting: finished reading database
2015-12-27 16:12:04 [DEBUG] lobster.plotting: reading database
2015-12-27 16:12:04 [DEBUG] lobster.plotting: finished reading database
2015-12-27 16:27:17 [DEBUG] lobster.plotting: reading database
2015-12-27 16:27:17 [DEBUG] lobster.plotting: finished reading database
```
End:
```
2016-01-06 12:55:35 [DEBUG] lobster.plotting: reading database
2016-01-06 12:55:54 [DEBUG] lobster.plotting: finished reading database
2016-01-06 13:11:33 [DEBUG] lobster.plotting: reading database
2016-01-06 13:11:52 [DEBUG] lobster.plotting: finished reading database
2016-01-06 13:26:52 [DEBUG] lobster.plotting: reading database
2016-01-06 13:27:11 [DEBUG] lobster.plotting: finished reading database
2016-01-06 13:42:08 [DEBUG] lobster.plotting: reading database
2016-01-06 13:42:27 [DEBUG] lobster.plotting: finished reading database
2016-01-06 13:57:44 [DEBUG] lobster.plotting: reading database
2016-01-06 13:58:02 [DEBUG] lobster.plotting: finished reading database
```

By the end, it's taking 15-20 seconds per plotting cycle, which happens every ~15 minutes.

Could it be that the retry logic is such that if the Lobster master happens to try to access the DB right at the start of a plotting cycle, that it will exhaust its retries before the cycle ends?  If so, we should think about a (hopefully) simple way to guard against this.  Random thoughts:
   * Certainly, 1 week into a run, we probably don't need to update the plots every ~15 minutes.  By then, probably once per hour is fine.  That would at least reduce the chance of a collision.
   * Ideally, the master should be able to force the plotting to stand aside if it needs access to the DB for the purpose of keeping the run going.
   * Plotting is strictly read-only on the DB, right?  Can't we access the DB without locking for read-only?  Or is there some way to access the DB in smaller chunks to make it easier for Lobster to break in.

In the end, if this produces < 1 crash per week, then it's probably not worth sinking a huge amount of effort into.  So, I'm not suggesting a complete rewrite of anything.  I'm just looking to see if there are easy tweaks.

**Comment by matz-e** [comment]
I think the culprit here is that we slurp in all the data form the jobs and turn them into a numpy array, which takes a while if you got O(1e6) jobs or so…

For you thoughts:

* Increasing the plotting time should be fairly easy to do. Note though that if we take more than a few seconds to read in the database, plotting may still block the regular processing, where Lobster returns into a database querying mode every 60s (we tell WQ to only wait 60s to deliver tasks to us). Thus this isn't a real fix.
* Possible fix. Don't know if that is possible with sqlite, though
* The problem is that processing modifies the database, which it can't do until plotting is done reading. We could do an iterative read, where we cache the data we've extracted so far via numpy, and only pull out of the database tasks that have finished since the last time we read. That plus an increased [timeout parameter for the connection in processing](https://docs.python.org/3/library/sqlite3.html?highlight=sqlite#sqlite3.connect) may be the ultimate solution for this? We can also crank the `@retry` decorator to wait in increasing time-steps instead of just retrying 5/10 times without waiting inbetween.
