### ISSUE TITLE
Add ca_info to DbsApi call

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#292]
I'm getting the following error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/python/2.7.6-cms/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/python/2.7.6-cms/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/commands/process.py", line 93, in sprint
    task_src = TaskProvider(config)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/core/source.py", line 146, in __init__
    dataset_info = wflow.dataset.get_info()
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/cmssw/dataset.py", line 96, in get_info
    res = self.query_database(self.dataset, self.dbs_instance, self.lumi_mask, self.file_based)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/cmssw/dataset.py", line 111, in query_database
    self.__apis[instance] = DASWrapper(dbs_url)
  File "/afs/crc.nd.edu/user/a/awoodard/.lobster/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 164, in __init__
    proxy=Socks5Proxy(proxy_url=self.proxy) if self.proxy else None)
  File "/afs/crc.nd.edu/user/a/awoodard/.lobster/lib/python2.7/site-packages/RestClient/RestApi.py", line 23, in __init__
    auth.configure_auth(self._curl)
  File "/afs/crc.nd.edu/user/a/awoodard/.lobster/lib/python2.7/site-packages/RestClient/AuthHandling/X509Auth.py", line 90, in configure_auth
    curl_object.setopt(curl_object.CAINFO, self._ca_info)
TypeError: invalid arguments to setopt
```
It looks like this error is because the DbsApi class has changed slightly and is now requiring `ca_info` to be set. @matze, @klannon: Should we specify a specific version of dbs-client in `install_dependencies.sh`? Or is it better to always check out the most up-to-date version (what we're currently doing) and fix our code if it breaks? The problem with not specifying a specific version is that we only find out that things have broken when we do a completely fresh lobster install, which is what happened here.

To reproduce this error you will need to update dbs-client.

**Comment by annawoodard** [comment]
I have pushed a hack which works for me in 23315b5. I'm not sure where the correct place to pull CAINFO from is. Maybe one of you knows: @klannon @matz-e @khurtado

**Comment by matz-e** [comment]
Argh… good that you found a fix! I had a workaround of loading the CRAB3 environment before loading the virtualenv to fix `py-curl`, the actual culprit. Thank you!

I tried fiddling with the `py-curl` dependency at some point, and I am clueless as to what the CERN folks are actually deploying so we get the right version. Doesn't help that I couldn't find a package history on the cheese shop either.

**Comment by annawoodard** [comment]
No problem! :smile:
