### ISSUE TITLE
Fix plotting crash

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#335]
```
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/a/awoodard/.lobster/lib/python2.7/site-packages/Lobster-1.5-py2.7.egg/lobster/actions.py", line 17, in runplots
    plotter.make_plots(foremen=foremen)
  File "/afs/crc.nd.edu/user/a/awoodard/.lobster/lib/python2.7/site-packages/Lobster-1.5-py2.7.egg/lobster/commands/plot.py", line 1115, in make_plots
    p.map(mp_call, self.__plotargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/python/2.7.6-cms/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/python/2.7.6-cms/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
ValueError: x has only one data point. bins or range kwarg must be given
```

**Comment by matz-e** [comment]
Do you have this in reproducible form? Also, when did this happen? I'm tempted to just wrap the call to the function in a `try: … except e: logger.error(…)`…

**Comment by annawoodard** [comment]
@matz-e: No, I don't have this in a reproducible form. I'm not sure how to do so, it seems to happen randomly. It just brought down my master again though. I'm going to run with the wrapper you suggested and see if that helps.

**Comment by annawoodard** [comment]
(Also, when I had this crash, I had zombie processes too.)

**Comment by matz-e** [comment]
That's annoying and weird… [this](https://github.com/matz-e/lobster/blob/master/lobster/actions.py#L12) is the function that does the plotting, and it should catch all exceptions? I.e. when plotting fails for any cause, the master should not be affected. Not sure what's going on, really…
