### ISSUE TITLE
Crash during startup prevents restart

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#429]
So, if you make a mistake like this in your config:
```
[.lobster] [klannon@earth test]$ tail -f /tmpscratch/users/klannon/tracklet_single_mu_newstubs_v01/process.err
    self.sprint()
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/./commands/process.py", line 176, in sprint
    task_src = TaskProvider(self.config)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/source.py", line 191, in __init__
    dataset_info = wflow.dataset.get_info()
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/cmssw/dataset.py", line 119, in get_info
    res = self.query_database(self.dataset, self.dbs_instance, self.lumi_mask, self.file_based)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/cmssw/dataset.py", line 140, in query_database
    raise ValueError('unable to retrive information for dataset {}'.format(dataset))
ValueError: unable to retrive information for dataset /RelValSingleMuPt1/CMSSW_6_2_0_SLHC26-DES23_62_V1_LHCCRefPU200-v1/GEN-SIM-DIGI-RAW
```

Then when you fix the typo in the dataset name, Lobster refuses to restart because it says this:
```
[.lobster] [klannon@earth test]$ lobster process tracklet.py
[Errno 2] No such file or directory: '/tmpscratch/users/klannon/tracklet_single_mu_newstubs_v01/config.pkl'
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/bin/lobster", line 9, in <module>
    load_entry_point('Lobster==1.5', 'console_scripts', 'lobster')()
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/ui.py", line 42, in boil
    cfg = config.Config.load(cfg.workdir)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/config.py", line 136, in load
    os.path.join(path, 'config.pkl')))
IOError: can't load configuration from /tmpscratch/users/klannon/tracklet_single_mu_newstubs_v01/config.pkl
```
I expect this means I need to wipe out my working directory and start over.  It would be nice if Lobster cleaned up after itself so that you didn't have to do it manually.  Is that feasible?

**Comment by matz-e** [comment]
(#341 would have prevented that)

**Comment by matz-e** [comment]
Note that an expired proxy will cause a crash, too, if the passphrase is entered wrong.

**Comment by annawoodard** [comment]
Also a non empty output directory will cause Lobster to exit without cleaning up the working directory.

**Comment by matz-e** [comment]
On it :)
