### ISSUE TITLE
ELK Crash (Time out Error?)

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#470]
I think this is distinct from the other two crashes.  If not, just close it.

```
2016-08-26 11:55:19 [CRITICAL] lobster.core: cannot recover from the following exception:
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/./commands/process.py", line 348, in sprint
    task_src.release(tasks)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/source.py", line 515, in release
    self.config.elk.index_summary(self.__store.workflow_status())
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/monitor/elk/interface.py", line 1154, in index_summary
    id=workflow_summary['label'])
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 460, in update
    doc_type, id, '_update'), params=params, body=body)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 102, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='elk.crc.nd.edu', port=9200): Read timed out. (read timeout=10))
```

**Comment by annawoodard** [comment]
There are two things we need to do here, I think: 1) catch this type of error so it doesn't bring the master down, and 2) understand and fix the error itself. I am testing something to address 1). As for 2): I'm guessing this error is related to load on `elk.crc.nd.edu`. @khurtado do you see any evidence of that in the logs there?

**Comment by matz-e** [comment]
I would propose creating a monitoring API that, when subclassed, wraps all functionality, catches all exceptions, and logs them (maybe with an error count per class?). Once my next procrastination spree comes around…

**Comment by klannon** [comment]
Just so the knowledge isn't lost, this error came from exhausting the disk on the ELK VM, which caused elasticsearch to stop responding.

**Comment by matz-e** [comment]
There's another issue open addressing this (#471) by Anna, closing.
