### ISSUE TITLE
One (Possibly Two) Bugs When Updating Config Parameters?

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#544]
Attempting to update the configuration for the skipping/failure thresholds produces the following error:

```
2017-01-04 23:19:19 [INFO] lobster.configure: updating item 0 of list 'extra_inputs' with value 'pu_files.txt' (old: '/tmpscratch/users/klannon/mcprod_ttW_alpha1273_filtered/v0_part3/digi_step/pu_files.txt')
2017-01-04 23:19:19 [ERROR] lobster.actions: failed to update configuration:
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/actions.py", line 47, in update_configuration
    self.config.update(new_config)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/util.py", line 207, in update
    ours[n].update(theirs[n])
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/util.py", line 217, in update
    setattr(self, arg, ours)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/util.py", line 123, in __setattr__
    raise AttributeError("can't change attribute {} of type {}".format(attr, type(self)))
AttributeError: can't change attribute extra_inputs of type <class 'lobster.core.workflow.Workflow'>
```

I think I may have avoided this error by editing the value of `extra_inputs` to match what Lobster was looking for instead of what it is normally in the configuration.  I can only think that Lobster must change the value of this parameter in memory, but it doesn't update `config.py` so if you make any other change to `config.py` then it chokes on this?  It's just a guess.

However, when I tried to restart as described above, I ran into this error:
```
2017-01-04 23:24:12 [INFO] lobster.configure: updating attribute 'threshold_for_skipping' with value '60' (old: '30')
2017-01-04 23:24:12 [ERROR] lobster.actions: caught exception while executing callback 'source.update_paused' with arguments ()
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/actions.py", line 66, in update_configuration
    call(*args)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/source.py", line 552, in update_paused
    self.__store.update_workflow_stats_paused()
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/unit.py", line 560, in update_workflow_stats_paused
    self.db.execute("update workflows set merged=0 where label=?", (m.label,))
AttributeError: 'function' object has no attribute 'label'
```

Lobster caught the exception and kept going, but it's not clear to me that the update actually worked.  Ideas?

**Comment by klannon** [comment]
OK, I think the following at least will not issue an error:

Change the original:
`for m in [r.family for r in roots]:`

To:
`for m in [f for f in r.family() for r in roots]:`

Then `m` should iterate over the elements in each `family` of each workflow.

As originally written, `m` iterates over family functions but then the code later tries to access the `label` member, which is a member of the `Workflow` class and not the `family` function.

Just adding a `()` to `family` in the above code means that each `m` is a generator object.

To me, it looks like the code as committed is just a bug.  I'm still not sure that the code I'm proposing actually achieves the desires of the original author, but at this point I'll try it and see if it does something sensible in my project.  @matz-e or @annawoodard please comment if you know what was supposed to be happening in this line...

**Comment by klannon** [comment]
Bah!  I couldn't get that to work, so I eventually settled for:
```
for r in roots:
    for m in r.family():
       ...
```
Which I think is what we were trying to do all along with the Python one-line version.  That at least compiles and runs without error.  (The proposal I made above gives a "compile time" error...)

**Comment by klannon** [comment]
Now, I'm trying to understand the original error.  Hypothesis is that it's this line:
https://github.com/matz-e/lobster/blob/master/lobster/core/workflow.py#L219

Combined with this line (and the one after):
https://github.com/matz-e/lobster/blob/master/lobster/core/workflow.py#L324

I think this is a passing-by-pointer rather than copying of array elements situation, with the end result and undesirable side effect being that the config object is modified during workflow creation.  I'd need to do some testing to verify that is the problem, but if someone with more Python knowledge than me sees this and know the answer, please let me know.

**Comment by klannon** [comment]
Rats!  Simple tests seem to suggest that's not quite what's happening.  The assignment on L325 should break the connection to the config version of extra_inputs.  But it's definitely true based on the original error that somewhere in Lobster, the values I set in the config (relative to the starting directory for Lobster) are getting replaced with a fully specified path to the working directory (i.e. `tmpscratch`).  Then when I try to update any part of config.py, it chokes because it sees the original `extra_inputs` instead of the internally updated value.  I'll have to think on it.  Still, I would think we'd want to make a copy of `extra_inputs` into the `Workflow` object rather than holding a pointer to the list in the config object.  Do you agree?

**Comment by klannon** [comment]
Turns out https://github.com/matz-e/lobster/pull/543/commits/a1c61b37159147be569e1f9b7948053ab40278a6 fixes my `family()` issue.  My plan is to upgrade to that PR and try to reproduce the `extra_inputs` error there.

**Comment by klannon** [comment]
(Thanks @matz-e!)
