### ISSUE TITLE
`datasets` option for publishing should be optional

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#570]
As reported by @PerilousApricot.
```
lobster publish /tmp/meloam/lobster_tuple_20170303-114319/config.py
Traceback (most recent call last):
  File "/gpfs22/home/meloam/projects/gen/from-jose/venv-lobster/bin/lobster", line 9, in <module>
    load_entry_point('Lobster==1.5-47cab60-clean', 'console_scripts', 'lobster')()
  File "/gpfs22/home/meloam/projects/gen/from-jose/venv-lobster/lib/python2.7/site-packages/lobster/ui.py", line 109, in boil
    args.plugin.run(args)
  File "/gpfs22/home/meloam/projects/gen/from-jose/venv-lobster/lib/python2.7/site-packages/lobster/cmssw/commands/publish.py", line 343, in run
    if len(args.datasets) > 0 and len(args.datasets) != len(args.workflows):
TypeError: object of type 'NoneType' has no len()
```

**Comment by matz-e** [comment]
Only if you specify the correct primary dataset in the DB first. I even forgot how that works…
