### ISSUE TITLE
Unable to open database with `lobster plot` command

### ISSUE THREAD

**Issue by WenzhaoLi** [matz-e/lobster#577]
```
(.lobster) [earth] ~/lobster/examples >lobster plot simple.py
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/w/wli12/.lobster/bin/lobster", line 11, in <module>
    load_entry_point('Lobster===1.5-3ef7a2f-dirty', 'console_scripts', 'lobster')()
  File "/afs/crc.nd.edu/user/w/wli12/.lobster/lib/python2.7/site-packages/lobster/ui.py", line 109, in boil
    args.plugin.run(args)
  File "/afs/crc.nd.edu/user/w/wli12/.lobster/lib/python2.7/site-packages/lobster/commands/plot.py", line 1511, in run
    p = Plotter(args.config, args.outdir, args.paper)
  File "/afs/crc.nd.edu/user/w/wli12/.lobster/lib/python2.7/site-packages/lobster/commands/plot.py", line 406, in __init__
    self.__store = unit.UnitStore(config)
  File "/afs/crc.nd.edu/user/w/wli12/.lobster/lib/python2.7/site-packages/lobster/core/unit.py", line 85, in __init__
    self.db = sqlite3.connect(self.db_path, timeout=90)
sqlite3.OperationalError: unable to open database file
```

**Comment by annawoodard** [comment]
I think the issue here is that the `workdir` in `simple.py` has a timestamp, so `lobster plot simple.py` is looking for the database in a working directory corresponding to the current timestamp. If you called `lobster plot /my/simple/workdir` I'd expect it to work. To consider this issue fixed, I recommend we add a more helpful error message for such cases.

**Comment by WenzhaoLi** [comment]
`lobster plot /my/simple/workdir` worked! I totally agree with you. Lobster can't find the `workdir` with current timestamp.

**Comment by matz-e** [comment]
I think this looks good for now. In general, I'm wondering if we should not move it out of the plotting to the UI module, and trigger it for all methods that do not create the working directory, i.e., all commands but `process`…

**Comment by annawoodard** [comment]
Good point @matz-e, I've updated the PR.
